### ISSUE TITLE
Tagging constraints as active

### ISSUE THREAD

**Issue by kaarthiksundar** [jump-dev/KNITRO.jl#154]
Is there a way to tag a constraint as active when we try to use SQP method to solve an NLP. I was thinking this will speed up the algorithm.

**Comment by frapac** [comment]
Unfortunately, there is no direct methods to tag a constraint as active in Knitro. 

When using the SQP algorithm, you could pass your initial guess concerning the active set `A_0` by using the method [KN_set_con_dual_init_values](https://www.artelys.com/docs/knitro//3_referenceManual/callableLibraryAPI.html#KN_set_con_dual_init_values), with 
```julia
KN_set_con_dual_init_values(kc, index_ineq_cons, lambda_init) 
```
with `lambda_init` an initial vector storing non-zero values for the constraints supposed to be active (to respect Knitro's convention, set `lambda_i` non-negative when `ci_(x) <= 0`, non-positive otherwise). If using JuMP, warmstart for constraints' duals will be supported soon (see https://github.com/JuliaOpt/JuMP.jl/pull/2214).

However, when using dual warmstart, you do not have any guarantee that the constraints you tag as active will remain so along the iterations of the SQP algorithm. 

Note also when using the SLQP algorithm, Knitro guesses the initial active set automatically by resolving a LP.

**Comment by frapac** [comment]
Closing this issue for now. Feel free to reopen if you have any additional comments.
