### ISSUE TITLE
Complementarity constraints can only be added all at once

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/KNITRO.jl#169]
Can we do something better?

Bridges won't work for that, because they act constraint by constraint.
Some possibilities are:
 - caching on knitro wrapper and only passing the solve is called
 - doing something in caching optimizer (does not seem very generic)
 - write a model transformation wrapper like Dualization.jl, that will cache complements and only pass once, if this is knitro specific, maybe its simples to do the first option.

**Comment by frapac** [comment]
I agree that the current solution is far from optimal. I see two solutions : 
* the improvement of MPEC's API is in Richard's TODO list, but that might take some time 
* otherwise, your first idea looks like a good solution in the short term.

I do not think that would be too hard to cache the MPEC structure in `KNITRO.Model` and then pass the MPEC structure to Knitro when `KN_solve` is called. I could work on a workaround soon.

**Comment by joaquimg** [comment]
solved by #170
