### ISSUE TITLE
Add support to Optimization.jl

### ISSUE THREAD

**Issue by jlperla** [jump-dev/KNITRO.jl#227]
For non-DSL usage, it would be great to have support within https://github.com/SciML/Optimization.jl   I think it could be a light wrapper for someone who knows the KNITRO API.

**Comment by frapac** [comment]
I am not very familiar with Optimization.jl, but can we use [OptimizationMOI](https://github.com/SciML/Optimization.jl/tree/master/lib/OptimizationMOI) to use directly Knitro inside Optimization.jl?

**Comment by jlperla** [comment]
Thanks @frapac  I just remain suspicious of wrappers intended to support DSL usage.  It seems like MOI could add in overhead/etc.  am not sure what the tradeoffs are there but DSL-inspired.

But maybe @ChrisRackauckas might have thoughts on limitations in the MOI style wrapping.  Maybe just an MOI example using Optimization.jl would suffice?  I have a student trying to use KNITRO but where JuMP isn't working very well for hiim.

Alternatively a variation on https://github.com/SciML/Optimization.jl/blob/master/lib/OptimizationNLopt/src/OptimizationNLopt.jl  would be a good start, even if it only starts by supporting unconstrained optimization.  But not sure what is gained/lost by skipping out on MOI.

**Comment by odow** [comment]
> For non-DSL usage, it would be great to have support within https://github.com/SciML/Optimization.jl I think it could be a light wrapper for someone who knows the KNITRO API.

I don't think this should go in KNITRO.jl. You're welcome to make a separate wrapper package like these: https://github.com/SciML/Optimization.jl/tree/master/lib.

> I just remain suspicious of wrappers intended to support DSL usage

JuMP is a DSL. But it doesn't pass the DSP to KNITRO. It just passes callbacks.

> I have a student trying to use KNITRO but where JuMP isn't working very well for him

What was the problem?

> Maybe just an MOI example using Optimization.jl would suffice

http://optimization.sciml.ai/stable/optimization_packages/mathoptinterface/

Although note that OptimizationMOI may struggle with large-scale problems (https://www.youtube.com/watch?v=tvBNQcuU-hY), so it isn't obvious that Optimization.jl will be much better than JuMP.

**Comment by dpo** [comment]
@jlperla Have a look at https://github.com/JuliaSmoothOptimizers/NLPModelsKnitro.jl.

**Comment by ChrisRackauckas** [comment]
> Although note that OptimizationMOI may struggle with large-scale problems (https://www.youtube.com/watch?v=tvBNQcuU-hY), so it isn't obvious that Optimization.jl will be much better than JuMP.

That only tested the symbolic derivatives vs symbolic JuMP. The point here is that this application doesn't fit into symbolic JuMP (this is using stuff like DifferenceEquations.jl etc, "non-DSL usage"), so the fast JuMP DSL stuff doesn't apply. Optimization.jl with AutoZygote() into MOI is what you'd want then.

**Comment by jlperla** [comment]
@odow  
> I don't think this should go in KNITRO.jl. You're welcome to make a separate wrapper package like these:

Totally agree.  I guess what I am suggesting is that (1) support for Optimization.jl should be part of the knitro toolset to maximize non-DSL approaches to using it; and (2) maybe even link from the frontpage of KNITRO.jl to that support as an example.  Since `SmoothOptimizers` has support for knitro then it is probably worth pointing that out from the front-page as well.

@ChrisRackauckas  Does the MOI optimizer wrapper support in `Optimization.jl` have any major downsides for performance/etc. or does it work really well and support all solver options?  If there are no downsides, then this issue should be closed and then maybe the only action items here are to add a pointer to the KNITRO example with Optimization.jl and the SmoothOptimizers on the KNITRO.jl front page?

**Comment by ChrisRackauckas** [comment]
> Does the MOI optimizer wrapper support in Optimization.jl have any major downsides for performance/etc. or does it work really well and support all solver options? 

It supports all that it can. There's four things involved here. There's the objective function, the derivative function, the symbolic objective, and the symbolic derivative. If the function cannot be represented symbolically (quasi-static or nonlinear size explosion or something), then the derivative cannot be represented symbolically. If symbolic information can be obtained, MOI allows this to be passed to solvers and some (but not all) solvers can take advantage of the symbolic information to do extra tricks for performance. If the function can be represented symbolically, there's a naïve derivative that ModelingToolkit will generate in Optimization.jl. JuMP's performance gain right now is in the symbolic derivative space with SymbolicAD.jl being an extension to the Symbolics.jl derivative, instead of just using the naïve one. But both systems will do some form of symbolic specialization in MOI when available.

However when the symbolic information is not available, then all you can do is pass a pointer to a Julia function for the objective and possibly a Julia function for the derivative. Optimization.jl then sets that up with a wide array of AD packages and says good luck: it'll do as well as you've written your objective with whatever AD choice you've chosen. That of course will not be as fast as something with all of the symbolic optimizations, but it's way more general and can apply to any equation. As far as we know, Optimization.jl does this optimally and we haven't seen any measurements showing that it's missing anything here. The measurements above, which were made in a confusing and out of context manner, were not about this case but instead about the symbolic case which you mentioned in the OP doesn't apply to this thread.

**Comment by odow** [comment]
What (if anything) is actionable here? Adding a link to NLPModels in the README? 

An KNITRO/Optimization wrapper can live in Optimization.jl/lib, so we won't be adding support for it in KNITRO.jl or `jump-dev`.

**Comment by jlperla** [comment]
> What (if anything) is actionable here? Adding a link to NLPModels in the README?

Yeah, I think pointers on the readme to `Optimization.jl` and NLPModels?  People don't realize they can use Knitro without JuMP (or dropping to the low-level interface which is tough to use).  Maybe an example of knitro+MOI+optimization.jl couldn't hurt over there.

> An KNITRO/Optimization wrapper can live in Optimization.jl/lib, 
Yes.  If the MOI wrapper proves insufficient then a follow-on for creating a separate wrapper in Optimization.jl might help if someone from Artelys was able to maintain it there.  Of course, if MOI wrapper does the same thing  with no significant overhead then that is unnecessary.

**Comment by odow** [comment]
> Maybe an example of knitro+MOI+optimization.jl couldn't hurt over there.

Here's where it should go: http://optimization.sciml.ai/stable/optimization_packages/mathoptinterface/#KNITRO.jl-(MathOptInterface)

**Comment by odow** [comment]
I made a bunch of changes to the README: https://github.com/jump-dev/KNITRO.jl/pull/229
